name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t my-app . | tee build.log
        cat build.log  # Print the build log to help identify issues

    - name: Run tests
      run: |
        docker run my-app npm test | tee test.log  
        cat test.log 
