name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image for testing
      run: |
        docker build -f Dockerfile.test -t my-app-test . | tee build.log
        cat build.log  # Print the build log to help identify issues

    - name: Run tests
      run: |
        docker run -e NODE_ENV=test my-app-test | tee test.log  
        cat test.log
